//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.01 at 02:43:35 PM CET 
//


package org.jboss;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jboss package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ComplexTypeOneElement_QNAME = new QName("http://jboss.org", "complexTypeOneElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jboss
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComplexTypeOne }
     * 
     */
    public ComplexTypeOne createComplexTypeOne() {
        return new ComplexTypeOne();
    }

    /**
     * Create an instance of {@link ComplexTypeTwo }
     * 
     */
    public ComplexTypeTwo createComplexTypeTwo() {
        return new ComplexTypeTwo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeOne }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jboss.org", name = "complexTypeOneElement")
    public JAXBElement<ComplexTypeOne> createComplexTypeOneElement(ComplexTypeOne value) {
        return new JAXBElement<ComplexTypeOne>(_ComplexTypeOneElement_QNAME, ComplexTypeOne.class, null, value);
    }

}
